const GUIDE_URL = 'https://docs.google.com/document/d/1MbvwJBDC_Pcic5_m6xuyCvDxMnV7vPcEojG97G71mto/edit';
const CREDIT = 'harryy2533';

function spec(begin, end, bytes, outbound, key = null) {
  return { beginPort: begin, endPort: end, bytes, isOutbound: outbound, key };
}

const PRESETS = [
  { id: 'port_3074_dl', name: '3074 Download', category: 'Ports',
    description: 'Connection to PvE enemies and the game itself. Blocks entity loading, buffs/debuffs, and wipe mechanics. Used for perma flags, GoS motes, DSC entrance, and many raid mechanics.',
    filters: [spec(3074, 3074, 1, false, '1')] },
  { id: 'port_3074_ul', name: '3074 Upload', category: 'Ports',
    description: 'Upload limit on port 3074. Used for Atheon oracle destruction, Crota insta-down, 3074 crash damage, and loadout desync with 3074 UL.',
    filters: [spec(3074, 3074, 1, true, '2')] },
  { id: 'port_7500', name: '7500 (Bungie API)', category: 'Ports',
    description: 'Connection to the Bungie API. Affects character menu, inventory swaps, rally banners, 7500 pre-damage, Duality chunks, and game crash methods.',
    filters: [spec(7500, 7515, 1, false, '6')] },
  { id: 'port_27k_dl', name: '27000 Download (27k DL)', category: 'Ports',
    description: 'Connection to other players (download). Used for unlimited res tokens, anti-kick, crash protection, and team desync methods.',
    filters: [spec(27000, 27200, 1, false, '5')] },
  { id: 'port_27k_ul', name: '27000 Upload (27k UL)', category: 'Ports',
    description: 'Connection to other players (upload). Used for team killing, loadout desync damage, and team desync. Very finicky — can error code if overused.',
    filters: [spec(27000, 27200, 1, true)] },
  { id: 'port_30k', name: '30000 Download (30k DL)', category: 'Ports',
    description: 'Connection to the game world. Prevents joining allies, forces Anteater/Baboon resync, and allows respawning with fireteam leader.',
    filters: [spec(30000, 30020, 1, false, '3')] },

  { id: 'mech_perma_flags', name: 'Perma Flags', category: 'Mechanics',
    description: 'Tick 3074 DL near a flag before the encounter and hold until after it starts. The flag stays placed. Untick when done.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'mech_gos_motes', name: 'GoS Motes', category: 'Mechanics',
    description: 'Limit 3074 DL before dunking motes. With 10 motes, dunk 4-5 times then untick to fill relays near instantly.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'mech_atheon_oracles', name: 'Atheon Oracles', category: 'Mechanics',
    description: 'Use 3074 UL to destroy all oracles and untick to pop them at once. Works on Atheon only, not the Oracle encounter.',
    filters: [spec(3074, 3074, 1, true)] },
  { id: 'mech_vow_cart', name: 'Vow Cart Skip', category: 'Mechanics',
    description: 'With 3 Knowledge, tick 3074 DL and stand on the cart. Cart won\'t move on your screen but will for others.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'mech_kf_self_res', name: 'KF Self-Res', category: 'Mechanics',
    description: 'Tick 30k DL and kill connections to respawn for free in King\'s Fall. You will lose ammo but keep ability energy.',
    filters: [spec(30000, 30020, 1, false)] },
  { id: 'mech_kf_totems', name: 'KF Totems', category: 'Mechanics',
    description: 'Limit while on totem plates so enemies respawn after being killed, duplicating their buff stacks.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'mech_ron_23', name: 'RoN 2-3 Skip', category: 'Mechanics',
    description: 'Tick 3074 DL before entering the 2-3 load zone to skip the wipe mechanic entirely.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'mech_crota_thrallway', name: 'Crota Thrallway', category: 'Mechanics',
    description: 'Limit as the bridge door opens. Another player picks up the chalice, you take it, walk to the end, untick, and deposit.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'mech_crota_insta_down', name: 'Crota Insta-Down', category: 'Mechanics',
    description: 'Limit 3074 UL after tractor is applied and sword Crota until teammates confirm he is downed.',
    filters: [spec(3074, 3074, 1, true)] },
  { id: 'mech_se_skip', name: 'SE 0-1 / 2-3 Skip', category: 'Mechanics',
    description: 'SE 0-1: Reconnect on load for instant Substratum spawn. SE 2-3: Tick 30k DL after Herald dies and kill connections until skip tells you to untick.',
    filters: [spec(30000, 30020, 1, false), spec(3074, 3074, 1, false)] },
  { id: 'mech_dsc_entrance', name: 'DSC Entrance', category: 'Mechanics',
    description: 'Limit 3074 DL with shelter buff and hold until end of maze to pass through unaffected by frostbite.',
    filters: [spec(3074, 3074, 1, false)] },

  { id: 'dmg_3074_crash', name: '3074 Crash Damage', category: 'Damage',
    description: 'Cast Thundercrash with Synthocepts, limit 3074 DL on impact while target is tractor debuffed. Untick when numbers turn white.',
    filters: [spec(3074, 3074, 1, false)] },
  { id: 'dmg_7500_predamage', name: '7500 Pre-Damage', category: 'Damage',
    description: 'Tick 7500, swap Duality to Lorentz in inventory, hold M1 and untick together. Shoots through Warpriest/Taniks shields.',
    filters: [spec(7500, 7515, 1, false)] },
  { id: 'dmg_7500_duality', name: '7500 Duality Chunks', category: 'Damage',
    description: 'Use 7500 with Duality and Lorentz for big boss chunks. Unreliable without pre-damage — use the Loadout Desync macro instead.',
    filters: [spec(7500, 7515, 1, false)] },
  { id: 'dmg_loadout_desync', name: 'Loadout Desync (Duality)', category: 'Damage',
    description: 'Make 3 Lorentz loadouts + 1 Duality loadout with completely different gear. Use the built-in Duality macro to cycle loadouts.',
    filters: [spec(3074, 3074, 1, true), spec(27000, 27200, 1, true)] },

  { id: 'util_anti_kick', name: 'Anti Kick', category: 'Utility',
    description: 'Tick 27k DL to prevent being kicked from fireteam. Unticking may kick you, but roster shows a grey spot until orbit.',
    filters: [spec(27000, 27200, 1, false)] },
  { id: 'util_res_tokens', name: 'Unlimited Res Tokens', category: 'Utility',
    description: 'Tick 27k DL during raid encounters to not consume res tokens. Does not work in GMs with shared revive pools.',
    filters: [spec(27000, 27200, 1, false)] },
  { id: 'util_game_crash', name: 'Game Crash (3P Emote)', category: 'Utility',
    description: 'Equip 3P emote, tick 7500, swap to 2P emote in same slot, spam emote to crash lobby. Tick 27k DL to protect yourself.',
    filters: [spec(7500, 7515, 1, false), spec(27000, 27200, 1, false)] },
  { id: 'util_teamkill', name: 'Team Kill', category: 'Utility',
    description: 'Method 1: Tick 27k UL+DL, swap shotguns, fire. Method 2: Tick 27k UL, swap loadouts 7s, die, respawn as ghost.',
    filters: [spec(27000, 27200, 1, true), spec(27000, 27200, 1, false)] },
];

module.exports = { PRESETS, GUIDE_URL, CREDIT };
